"""
Discharge summary output schema — the final structured output produced by the agent.
"""

from pydantic import BaseModel, Field
from typing import Optional
from app.models.clinical import MedicationChange, LabResult, ClinicalFlag, ConflictInfo


class DischargeSummarySection(BaseModel):
    """A single section of the discharge summary."""
    title: str
    content: str
    sources: list[str] = Field(default_factory=list)  # Source references
    has_missing_data: bool = False
    has_conflict: bool = False
    flags: list[str] = Field(default_factory=list)


class DischargeSummary(BaseModel):
    """Complete structured discharge summary draft."""

    # Header
    is_draft: bool = True
    draft_notice: str = "⚠️ DRAFT — FOR CLINICIAN REVIEW ONLY. This document was generated by an AI agent and requires clinical verification before use."

    # Patient Info
    patient_demographics: DischargeSummarySection
    admission_date: DischargeSummarySection
    discharge_date: DischargeSummarySection

    # Diagnoses
    principal_diagnosis: DischargeSummarySection
    secondary_diagnoses: DischargeSummarySection

    # Course
    hospital_course: DischargeSummarySection
    procedures: DischargeSummarySection

    # Medications
    discharge_medications: DischargeSummarySection
    medication_changes: list[MedicationChange] = Field(default_factory=list)

    # Safety
    allergies: DischargeSummarySection

    # Discharge Plan
    follow_up_instructions: DischargeSummarySection
    pending_results: DischargeSummarySection
    discharge_condition: DischargeSummarySection

    # Flags & Conflicts
    clinical_flags: list[ClinicalFlag] = Field(default_factory=list)
    conflicts: list[ConflictInfo] = Field(default_factory=list)

    def to_markdown(self) -> str:
        """Render the discharge summary as formatted markdown."""
        lines = []
        lines.append("# DISCHARGE SUMMARY — DRAFT")
        lines.append("")
        lines.append(f"> {self.draft_notice}")
        lines.append("")

        # Flags summary at the top
        if self.clinical_flags:
            lines.append("## ⚠️ FLAGS FOR CLINICIAN REVIEW")
            lines.append("")
            for flag in self.clinical_flags:
                severity_icon = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🔵"}.get(flag.severity, "⚪")
                lines.append(f"- {severity_icon} **[{flag.flag_type}]** {flag.description}")
                if flag.source_references:
                    lines.append(f"  - Sources: {', '.join(flag.source_references)}")
            lines.append("")

        # Conflicts
        if self.conflicts:
            lines.append("## ⚠️ CONFLICTS DETECTED")
            lines.append("")
            for conflict in self.conflicts:
                lines.append(f"- **{conflict.field}**:")
                lines.append(f"  - Version 1 ({conflict.source_1}): {conflict.value_1}")
                lines.append(f"  - Version 2 ({conflict.source_2}): {conflict.value_2}")
                if conflict.resolution:
                    lines.append(f"  - Resolution: {conflict.resolution}")
                else:
                    lines.append(f"  - ❗ **UNRESOLVED — REQUIRES CLINICIAN REVIEW**")
            lines.append("")

        # Sections
        sections = [
            self.patient_demographics,
            self.admission_date,
            self.discharge_date,
            self.principal_diagnosis,
            self.secondary_diagnoses,
            self.hospital_course,
            self.procedures,
            self.discharge_medications,
            self.allergies,
            self.follow_up_instructions,
            self.pending_results,
            self.discharge_condition,
        ]

        for section in sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            if section.sources:
                lines.append("")
                lines.append(f"*Sources: {', '.join(section.sources)}*")
            if section.flags:
                lines.append("")
                for flag in section.flags:
                    lines.append(f"> ⚠️ {flag}")
            lines.append("")

        # Medication changes detail
        if self.medication_changes:
            lines.append("## MEDICATION RECONCILIATION DETAIL")
            lines.append("")
            lines.append("| Medication | Change | Old Dose | New Dose | Reason |")
            lines.append("|-----------|--------|----------|----------|--------|")
            for mc in self.medication_changes:
                old = mc.old_dose or "—"
                new = mc.new_dose or "—"
                reason = mc.reason or "**NO DOCUMENTED REASON ⚠️**"
                flag = " 🚩" if mc.flagged else ""
                lines.append(f"| {mc.medication_name} | {mc.change_type}{flag} | {old} | {new} | {reason} |")
            lines.append("")

        lines.append("---")
        lines.append("*This is an AI-generated draft. All clinical information requires verification by a qualified clinician.*")

        return "\n".join(lines)
